apiVersion: v1
kind: Pod
spec:
  containers:
  - env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /auth/credentials.json
    volumeMounts:
    - name: tidb-service-account
      mountPath: "/auth"
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  nodeSelector:
    "kubernetes.io/hostname": "gke-tidb-pool-1-60d488aa-kk1v"
  volumes:
  - name: tidb-service-account
    secret:
      secretName: tidb-bt-key
status: {}
